### ISSUE TITLE
Insert soundcloud widget on Conferences Program page

### ISSUE THREAD

**Issue by verarojman** [Platoniq/decidim-uclg#19]
Música al programa: Han optat per Soundcloud. Estan creant una llista de que és la que volen que soni. Aqui la teniu: https://soundcloud.com/uclg/sets/uclg-retreat-campus-2021

Widget petit (autoplay?)

**Comment by microstudi** [comment]
Sip, confio que trobaras la millor manera de posar-ho per alla.
![image](https://user-images.githubusercontent.com/1401520/106433400-73fce380-6470-11eb-8186-9caa058e512d.png)

**Comment by verarojman** [comment]
Closed by #26
