### ISSUE TITLE
Add Watermark to info page and Program (EB 2021)

### ISSUE THREAD

**Issue by NilHomedes** [Platoniq/decidim-uclg#52]
Hola!

Cal inserir una marca d'aigua al Programa i al inici del EB 2021 (conferences). Concretament aquí: 

- https://www.uclgmeets.org/conferences/ProgramEB21 
- https://www.uclgmeets.org/conferences/ProgramEB21/program/1242 

Demanen que quedi a la banda esquerra del programa, i d'un tamany com el que us mostro aquí:
![Screenshot_2021-05-04 Program - A Global Community That Cares - United Cities and Local Governments (6)](https://user-images.githubusercontent.com/71442847/117026851-6a4b7c00-acfc-11eb-90aa-30117c1508db.png)

La idea es que estigui present en tot l'scroll down, osigui que hauríeu de repetir vàries vegades la imatge. 

En aquest screenshot que us he posat d'exemple la imatge està amb aquests valors del inspector del Mozilla:
```
background-size: 15%;
background-position: top left;
background-repeat: no-repeat;
```

Adjunto l'arxiu de la imatge (espero que conservi qualitat)
![watermark4](https://user-images.githubusercontent.com/71442847/117028935-78020100-acfe-11eb-8e5e-8b5efdca6309.png)

Imagino que només cal replicar el que ja vau fer a: #41 

Si voleu podem fer-ho directament a producció, i si cal ajustar ja ho farem.

Gràcies!

**Comment by microstudi** [comment]
Caram que creatius!

**Comment by NilHomedes** [comment]
@microstudi @verarojman Com ho tenim això? Dimarts comença l'executive Bureau i em demanen tenir-ho fet.
